name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang llvm libbpf-dev linux-headers-generic gcc-multilib make
    
    - name: Generate eBPF
      env:
        CC: clang
      run: go generate ./...
    
    - name: Build
      run: go build -v -o bpfview
    
    - name: Test
      run: go test -v ./...
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bpfview
        path: bpfview
        
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: bpfview
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: bpfview
