name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - name: al2023
            kernel: '6.1'
            vmlinux: 'vmlinux-6.1-al2023.h'
            description: 'Amazon Linux 2023 (kernel 6.1)'
          - name: ubuntu2404
            kernel: '6.8'
            vmlinux: 'vmlinux-6.8-ubuntu.h'
            description: 'Ubuntu 24.04 LTS (kernel 6.8)'
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang llvm libbpf-dev linux-headers-generic gcc-multilib make
    
    - name: Setup vmlinux.h
      run: |
        cp kernels/${{ matrix.platform.vmlinux }} bpf/vmlinux.h
    
    - name: Generate eBPF
      env:
        CC: clang
      run: go generate ./...
    
    - name: Build
      run: |
        go build -v -o bpfview-${{ matrix.platform.name }}
        # Create checksum
        sha256sum bpfview-${{ matrix.platform.name }} > bpfview-${{ matrix.platform.name }}.sha256
        # Create description file
        echo "BPFView binary for ${{ matrix.platform.description }}" > bpfview-${{ matrix.platform.name }}.txt
    
    - name: Test
      run: go test -v ./...
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bpfview-${{ matrix.platform.name }}
        path: |
          bpfview-${{ matrix.platform.name }}
          bpfview-${{ matrix.platform.name }}.sha256
          bpfview-${{ matrix.platform.name }}.txt
        
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: bpfview
        
    - name: Prepare release files
      run: |
        mkdir release
        cp artifacts/bpfview-*/bpfview-* release/
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        generate_release_notes: true